
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-secret
spec:
  secretStoreRef:
    name: aws-ssm
    kind: SecretStore
  target:
    name: demo-secret
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: /prod/db/password
